openapi: 3.0.3
info:
  title: Pipeline Backend Admin Healthz API
  version: 0.1.0
security:
- bearerAuth: []
tags:
- name: Healthz
paths:
  /healthz:
    get:
      responses:
        '200':
          description: Default Response
      tags:
      - Healthz
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
