openapi: 3.2.0
info:
  title: Pipeline Backend Readyz API
  version: 0.1.0
security:
- bearerAuth: []
tags:
- name: Readyz
paths:
  /readyz:
    get:
      responses:
        '200':
          description: Default Response
      tags:
      - Readyz
      summary: Get readyz
      x-summary-source: derived
      operationId: getReadyz
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
