openapi: 3.2.0
info:
  title: Pipeline Backend Healthz API
  version: 0.1.0
security:
- bearerAuth: []
tags:
- name: Healthz
paths:
  /healthz:
    get:
      responses:
        '200':
          description: Default Response
      tags:
      - Healthz
      summary: Get healthz
      x-summary-source: derived
      operationId: getHealthz
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
