openapi: 3.2.0
info:
  title: Pipeline Backend Ai Results API
  version: 0.1.0
security:
- bearerAuth: []
tags:
- name: Ai Results
paths:
  /v1/ai-results:
    get:
      parameters:
      - schema:
          type: string
          format: uuid
        in: query
        name: customerId
        required: false
      - schema:
          type: string
        in: query
        name: handlingUnit
        required: false
      - schema:
          type: string
        in: query
        name: shipmentId
        required: false
      - schema:
          type: string
          enum:
          - measurement_v1
          - object_detection_v1
        in: query
        name: resultType
        required: false
      - schema:
          type: boolean
          default: false
        in: query
        name: includeUnreviewed
        required: false
      responses:
        '200':
          description: Default Response
      tags:
      - Ai Results
      summary: Get ai results
      x-summary-source: derived
      operationId: getV1AiResults
      x-operation-id-source: derived
  /v1/ai-results/{resultId}:
    get:
      parameters:
      - schema:
          type: string
          format: uuid
        in: path
        name: resultId
        required: true
      responses:
        '200':
          description: Default Response
      tags:
      - Ai Results
      summary: Get ai results by result id
      x-summary-source: derived
      operationId: getV1AiResultsByResultId
      x-operation-id-source: derived
  /v1/ai-results/{resultId}/artifacts/{artifactKind}/url:
    post:
      parameters:
      - schema:
          type: string
          format: uuid
        in: path
        name: resultId
        required: true
      - schema:
          type: string
          enum:
          - image
          - modelPly
        in: path
        name: artifactKind
        required: true
      responses:
        '200':
          description: Default Response
      tags:
      - Ai Results
      summary: Create ai results by result id artifacts by artifact kind url
      x-summary-source: derived
      operationId: postV1AiResultsByResultIdArtifactsByArtifactKindUrl
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
